"""Add RoutingProfileModel

Revision ID: babd94dfa8e6
Revises: 009_unique_delegation
Create Date: 2026-09-21 08:35:43.848508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'babd94dfa8e6'
down_revision: Union[str, None] = '009_unique_delegation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('policy_type', sa.String(length=32), nullable=False),
    sa.Column('provider_override', sa.String(length=64), nullable=True),
    sa.Column('model_override', sa.String(length=128), nullable=True),
    sa.Column('reasoning_effort', sa.String(length=32), nullable=False),
    sa.Column('privacy_requirement', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_profiles_is_active'), 'routing_profiles', ['is_active'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routing_profiles_is_active'), table_name='routing_profiles')
    op.drop_table('routing_profiles')
    # ### end Alembic commands ###
