"""add_routing_snapshots_and_resolver

Revision ID: c98b2edcf21d
Revises: babd94dfa8e6
Create Date: 2026-09-21 08:48:46.575974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98b2edcf21d'
down_revision: Union[str, None] = 'babd94dfa8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_routing_assignments',
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('routing_profile_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['routing_profile_id'], ['routing_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_name')
    )
    op.create_index(op.f('ix_project_routing_assignments_routing_profile_id'), 'project_routing_assignments', ['routing_profile_id'], unique=False)
    op.add_column('routing_profiles', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('routing_profiles', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_routing_profiles_is_default'), 'routing_profiles', ['is_default'], unique=False)
    op.add_column('routing_profiles', sa.Column('global_privacy_policy', sa.String(length=32), nullable=False))
    op.add_column('routing_profiles', sa.Column('global_fallback_policy', sa.String(length=32), nullable=False))
    op.add_column('routing_profiles', sa.Column('cost_preference', sa.String(length=32), nullable=False))
    op.add_column('routing_profiles', sa.Column('latency_preference', sa.String(length=32), nullable=False))
    op.add_column('routing_profiles', sa.Column('routes_json', sa.JSON(), nullable=False))
    op.drop_column('routing_profiles', 'privacy_requirement')
    op.drop_column('routing_profiles', 'policy_type')
    op.drop_column('routing_profiles', 'reasoning_effort')
    op.drop_column('routing_profiles', 'model_override')
    op.drop_column('routing_profiles', 'provider_override')
    op.add_column('runs', sa.Column('routing_snapshot_json', sa.JSON(), nullable=False))
    op.add_column('sessions', sa.Column('routing_profile_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_sessions_routing_profile_id'), 'sessions', ['routing_profile_id'], unique=False)
    
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        with op.batch_alter_table('sessions') as batch_op:
            batch_op.create_foreign_key('fk_sessions_routing_profile_id', 'routing_profiles', ['routing_profile_id'], ['id'], ondelete='SET NULL')
    else:
        op.create_foreign_key('fk_sessions_routing_profile_id', 'sessions', 'routing_profiles', ['routing_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        with op.batch_alter_table('sessions') as batch_op:
            batch_op.drop_constraint('fk_sessions_routing_profile_id', type_='foreignkey')
    else:
        op.drop_constraint('fk_sessions_routing_profile_id', 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_routing_profile_id'), table_name='sessions')
    op.drop_column('sessions', 'routing_profile_id')
    op.drop_column('runs', 'routing_snapshot_json')
    op.add_column('routing_profiles', sa.Column('provider_override', sa.VARCHAR(length=64), nullable=True))
    op.add_column('routing_profiles', sa.Column('model_override', sa.VARCHAR(length=128), nullable=True))
    op.add_column('routing_profiles', sa.Column('reasoning_effort', sa.VARCHAR(length=32), nullable=False))
    op.add_column('routing_profiles', sa.Column('policy_type', sa.VARCHAR(length=32), nullable=False))
    op.add_column('routing_profiles', sa.Column('privacy_requirement', sa.VARCHAR(length=32), nullable=False))
    op.drop_column('routing_profiles', 'routes_json')
    op.drop_column('routing_profiles', 'latency_preference')
    op.drop_column('routing_profiles', 'cost_preference')
    op.drop_column('routing_profiles', 'global_fallback_policy')
    op.drop_column('routing_profiles', 'global_privacy_policy')
    op.drop_index(op.f('ix_routing_profiles_is_default'), table_name='routing_profiles')
    op.drop_column('routing_profiles', 'is_default')
    op.drop_column('routing_profiles', 'version')
    op.drop_index(op.f('ix_project_routing_assignments_routing_profile_id'), table_name='project_routing_assignments')
    op.drop_table('project_routing_assignments')
    # ### end Alembic commands ###
