"""Unit tests for the provider-neutral embedding abstraction layer."""

import pytest
from app.memory.embeddings.base import EmbeddingRequest
from app.memory.embeddings.mock_provider import MockEmbeddingProvider
from app.memory.embeddings.router import (
    EmbeddingModelMismatchError,
    EmbeddingRouter,
)


@pytest.mark.asyncio
async def test_mock_embedding_provider_deterministic_generation():
    """Verify that identical texts produce identical vectors and different texts produce different vectors."""
    provider = MockEmbeddingProvider(dimension=1536, model_name="test-mock-v1")
    assert provider.name == "mock"
    assert provider.dimension == 1536
    assert provider.model_name == "test-mock-v1"

    req1 = EmbeddingRequest(texts=["Atlas uses Python 3.12"])
    res1 = await provider.embed(req1)
    assert res1.dimension == 1536
    assert res1.model == "test-mock-v1"
    assert len(res1.embeddings) == 1
    assert len(res1.embeddings[0]) == 1536

    # Identical query produces identical vector
    q_vec = await provider.embed_query("Atlas uses Python 3.12")
    assert q_vec == res1.embeddings[0]

    # Different text produces different vector
    other_vec = await provider.embed_query("Completely unrelated topic about astronomy")
    assert other_vec != q_vec


@pytest.mark.asyncio
async def test_embedding_router_dimension_validation_and_mismatch():
    """Verify that EmbeddingRouter detects and rejects vector dimension mismatches."""
    mock_1536 = MockEmbeddingProvider(dimension=1536, model_name="mock-1536")
    router = EmbeddingRouter(
        providers={"mock": mock_1536},
        default_provider="mock",
    )

    assert router.current_dimension == 1536
    assert router.current_model_name == "mock-1536"

    # Valid vector check
    valid_vec = [0.1] * 1536
    router.validate_vector_compatibility(valid_vec, model_name="mock-1536")

    # Wrong dimension must raise EmbeddingModelMismatchError
    invalid_dim_vec = [0.1] * 512
    with pytest.raises(EmbeddingModelMismatchError, match="dimension 512 does not match"):
        router.validate_vector_compatibility(invalid_dim_vec, model_name="mock-1536")

    # Mismatched model name must raise EmbeddingModelMismatchError
    with pytest.raises(EmbeddingModelMismatchError, match="Re-embedding required"):
        router.validate_vector_compatibility(valid_vec, model_name="old-legacy-model-v0")


@pytest.mark.asyncio
async def test_embedding_space_isolation_adversarial(test_db_session):
    """
    Adversarial test: Two embedding models produce vectors of the same dimension (1536),
    but represent completely different vector spaces.
    Verify that query search with model-A strictly excludes all memories embedded with model-B.
    """
    from app.db.models import MemoryModel
    from app.memory.base import MemoryType
    from app.memory.stores.sqlite_store import SqliteSemanticStore

    store = SqliteSemanticStore(test_db_session)

    # Identical 1536-dim vector generated by two distinct models
    vec = [0.05] * 1536

    mem_model_a = MemoryModel(
        memory_type=MemoryType.SEMANTIC.value,
        content="Knowledge encoded with text-embedding-ada-002",
        embedding=vec,
        embedding_model="text-embedding-ada-002",
        embedding_dim=1536,
        is_active=True,
    )
    mem_model_b = MemoryModel(
        memory_type=MemoryType.SEMANTIC.value,
        content="Knowledge encoded with text-embedding-3-small",
        embedding=vec,
        embedding_model="text-embedding-3-small",
        embedding_dim=1536,
        is_active=True,
    )

    await store.store(mem_model_a)
    await store.store(mem_model_b)

    # Query with text-embedding-3-small: Must ONLY return mem_model_b, NEVER mem_model_a
    results_b = await store.search(
        query_vector=vec,
        limit=10,
        min_similarity=0.0,
        embedding_model="text-embedding-3-small",
        embedding_dim=1536,
    )
    assert len(results_b) == 1
    assert results_b[0][0].id == mem_model_b.id
    assert results_b[0][0].embedding_model == "text-embedding-3-small"

    # Query with text-embedding-ada-002: Must ONLY return mem_model_a
    results_a = await store.search(
        query_vector=vec,
        limit=10,
        min_similarity=0.0,
        embedding_model="text-embedding-ada-002",
        embedding_dim=1536,
    )
    assert len(results_a) == 1
    assert results_a[0][0].id == mem_model_a.id
    assert results_a[0][0].embedding_model == "text-embedding-ada-002"

